name = "prng"
version = "3.0.2"
description = "A Pure Random Number Generator"

licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "prng" }
gleam = ">= 0.33.0"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_bitwise = "~> 1.3"

[dev-dependencies]
gleeunit = "~> 1.0"
