name = "prng"
version = "3.0.0"
description = "A Pure Random Number Generator"

licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "prng" }
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.31"
gleam_bitwise = "~> 1.3"

[dev-dependencies]
gleeunit = "~> 0.10"
